### ISSUE TITLE
활동 그룹 관련 API의 응답 내용 수정

### ISSUE THREAD

**Issue by mingmingmon** [KGU-C-Lab/clab-platforms-server#467]
### Describe

@Jeong-Ag님이 활동 그룹 부분의 API 연동 작업을 하시면서 응답으로 반환되는 특정 id 값 이외에 추가적인 정보를 함께 반환하시길 원해 해당 부분들을 수정하고자 합니다.

### Tasks

- [x] 활동 그룹 게시판 생성, 삭제, 수정 API의 반환값을 id, groupId, parentId로 수정
- [x] 신청 멤버 상태 변경 API의 반환값을 groupId로 수정. 이때 groupId 값은 id 변수명으로 매핑
- [x] 활동 상태 변경 API의 반환값을 groupId, status로 수정. 이때 groupId 값은 id 변수명으로 매핑
