### ISSUE TITLE
QA 피드백에 따른 활동 그룹 로직 수정

### ISSUE THREAD

**Issue by mingmingmon** [KGU-C-Lab/clab-platforms-server#499]
### Describe

1차 QA 후 활동그룹 관련 수정사항입니다

### Tasks

- [x] 활동 생성, 수정 시 content의 글자수 제한을 200으로 설정. 초과할 경우 예외처리 후 노션에 명시
- [x] 나의 활동 참여 상태 api 작성
- [x] 팀원 상태 변경 api 작성
- [x] 활동 생성 시 github url 입력 경우의 수 처리
- [x] 주차별 활동 파일 업로드 API 추가(`/api/v1/weekly-activity/{activiryGroupId}`)

### 나의 활동 참여 상태 API 작성에 대한 내용 정리

해당 내용은 @Jeong-Ag 님과 사전 협의된 사항입니다.

![image](https://github.com/user-attachments/assets/b14f54d3-aa7a-4c4d-a9f2-b1a2583dd622)

- **현재 진행 중인 그룹**: 변경 없음
- **나의 활동**:
    - **현재**: 내가 참여한 또는 참여했던 활동이 조회됨
    - **수정**: 각 활동의 진행 상태(현재 진행 중인지, 종료되었는지)에 대한 정보가 추가됨
- **나의 지원 API 추가**: 내가 그동안 지원했던 활동 목록을 반환하며, 각 활동의 진행 상태(현재 진행 중인지 여부)를 함께 포함
