### ISSUE TITLE
QA 피드백에 따른 활동 게시판 로직 수정

### ISSUE THREAD

**Issue by mingmingmon** [KGU-C-Lab/clab-platforms-server#500]
### Describe

1차 QA 후 ActivityGroupBoard 관련 수정사항입니다.

### Tasks

- [ ] 과제 제출을 1회만 가능하도록 validation 추가
- [ ] 과제 수정 시 updatedAt 정보가 수정되는지 확인
- [ ] 게시글 카테고리별 조회 권한 제어
- [ ] 게시글 카테고리별 생성 권한 제어
